apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: laravel
  template:
    metadata:
      labels:
        component: laravel
    spec:
      restartPolicy: Always
      containers:
      - name: laravel
        image: skaffold_laravel
        ports:
        - containerPort: 8888