apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      restartPolicy: Always
      containers:
      - name: client
        image: skaffold_client
        ports:
          - containerPort: 7777
